const INIT = 'INIT'
const SET_FORM = 'SET_FORM'
const INITMENU = 'INITMENU'
const INITMENU2 = 'INITMENU2'
const USERINFO = 'USERINFO'
const CHANGESUBMENU = 'CHANGESUBMENU'
const CHANGEITEM = 'CHANGEITEM'
const CRUMBINFO = 'CRUMBINFO'
export {
  SET_FORM,
  INIT,
  INITMENU,
  INITMENU2,
  USERINFO,
  CHANGESUBMENU,
  CHANGEITEM,
  CRUMBINFO
}
